name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    name: Firebase-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BFGM_E_V }}"
          channelId: live
          projectId: bfgm-e-v
