name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    name: Firebase-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Check package.json
        run: cat package.json
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-server:
    name: Heroku-Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check package.json
        run: |
          cd server
          cat requirements.txt
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          directory: server
          file_name: .env
      - name: Add backend remote origin
        run: git remote add heroku-server https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/bfgm.git
      - name: Deploy backend to Heroku
        run: git push heroku-server `git subtree split --prefix server master`:refs/heads/master --force
