name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    name: Firebase-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Check package.json
        run: cat package.json
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-cloud-functions:
    name: Firebase-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Check packages
        run: |
          cd functions
          cat package.json
      - name: Install npm packages
        run: |
          cd functions
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-server:
    name: Heroku-Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check package.json
        run: |
          cd server
          cat requirements.txt
      - name: Add backend remote origin
        run: git remote add heroku-server https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/bfgm.git
      - name: Create env file for server
        run: |
          cd server
          touch .env
          echo NOTION_ACCESS_TOKEN=${{ secrets.NOTION_ACCESS_TOKEN }} >> .env
          cat .env
      - name: Add env to git
        run: |
          git config --global user.email "hi@bfgm.eu"
          git config --global user.name "BFGM CI SERVER"
          git add .
          git commit -am "fix:add-env-file"
      - name: Deploy backend to Heroku
        run: git push heroku-server `git subtree split --prefix server master`:refs/heads/master --force
