name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    name: Firebase-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Check package.json
        run: cat package.json
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-server:
    name: Heroku-Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check package.json
        run: |
          cd server
          cat package.json
      - name: Init Heroku Action
        run: cd server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bfgm"
          heroku_email: "nguyenminhducdd@yahoo.de"
